stages: [deploy]

deploy-prod:
  stage: deploy
  tags: [relay-preprod]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "relay-fixes"'
  variables:
    COMPOSE_PROJECT_NAME: relay
  script:
    - docker compose up -d --build --remove-orphans
    - docker image prune -f
    - docker compose ps
